[widget]
label = "Note Rapide"
button_text = "Chiudi"
position_type = "preset"
position = "top-right"
always_on_top = true
transparent = true

[action]
command = "notify-send 'Hai cliccato il widget!'"
